/*
Farcaster API V1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the RecasterPfp type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RecasterPfp{}

// RecasterPfp struct for RecasterPfp
type RecasterPfp struct {
	// The URL of the recaster's profile picture.
	Url *string `json:"url,omitempty"`
}

// NewRecasterPfp instantiates a new RecasterPfp object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewRecasterPfp() *RecasterPfp {
	this := RecasterPfp{}
	return &this
}

// NewRecasterPfpWithDefaults instantiates a new RecasterPfp object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewRecasterPfpWithDefaults() *RecasterPfp {
	this := RecasterPfp{}
	return &this
}

// GetUrl returns the Url field value if set, zero value otherwise.
func (o *RecasterPfp) GetUrl() string {
	if o == nil || IsNil(o.Url) {
		var ret string
		return ret
	}
	return *o.Url
}

// GetUrlOk returns a tuple with the Url field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *RecasterPfp) GetUrlOk() (*string, bool) {
	if o == nil || IsNil(o.Url) {
		return nil, false
	}
	return o.Url, true
}

// HasUrl returns a boolean if a field has been set.
func (o *RecasterPfp) HasUrl() bool {
	if o != nil && !IsNil(o.Url) {
		return true
	}

	return false
}

// SetUrl gets a reference to the given string and assigns it to the Url field.
func (o *RecasterPfp) SetUrl(v string) {
	o.Url = &v
}

func (o RecasterPfp) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RecasterPfp) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Url) {
		toSerialize["url"] = o.Url
	}
	return toSerialize, nil
}

type NullableRecasterPfp struct {
	value *RecasterPfp
	isSet bool
}

func (v NullableRecasterPfp) Get() *RecasterPfp {
	return v.value
}

func (v *NullableRecasterPfp) Set(val *RecasterPfp) {
	v.value = val
	v.isSet = true
}

func (v NullableRecasterPfp) IsSet() bool {
	return v.isSet
}

func (v *NullableRecasterPfp) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRecasterPfp(val *RecasterPfp) *NullableRecasterPfp {
	return &NullableRecasterPfp{value: val, isSet: true}
}

func (v NullableRecasterPfp) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRecasterPfp) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


