/*
Farcaster API V1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ReactionsAndRecastsResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReactionsAndRecastsResponse{}

// ReactionsAndRecastsResponse struct for ReactionsAndRecastsResponse
type ReactionsAndRecastsResponse struct {
	Result *ReactionsAndRecastsResponseResult `json:"result,omitempty"`
}

// NewReactionsAndRecastsResponse instantiates a new ReactionsAndRecastsResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReactionsAndRecastsResponse() *ReactionsAndRecastsResponse {
	this := ReactionsAndRecastsResponse{}
	return &this
}

// NewReactionsAndRecastsResponseWithDefaults instantiates a new ReactionsAndRecastsResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReactionsAndRecastsResponseWithDefaults() *ReactionsAndRecastsResponse {
	this := ReactionsAndRecastsResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *ReactionsAndRecastsResponse) GetResult() ReactionsAndRecastsResponseResult {
	if o == nil || IsNil(o.Result) {
		var ret ReactionsAndRecastsResponseResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ReactionsAndRecastsResponse) GetResultOk() (*ReactionsAndRecastsResponseResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *ReactionsAndRecastsResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given ReactionsAndRecastsResponseResult and assigns it to the Result field.
func (o *ReactionsAndRecastsResponse) SetResult(v ReactionsAndRecastsResponseResult) {
	o.Result = &v
}

func (o ReactionsAndRecastsResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReactionsAndRecastsResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableReactionsAndRecastsResponse struct {
	value *ReactionsAndRecastsResponse
	isSet bool
}

func (v NullableReactionsAndRecastsResponse) Get() *ReactionsAndRecastsResponse {
	return v.value
}

func (v *NullableReactionsAndRecastsResponse) Set(val *ReactionsAndRecastsResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableReactionsAndRecastsResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableReactionsAndRecastsResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReactionsAndRecastsResponse(val *ReactionsAndRecastsResponse) *NullableReactionsAndRecastsResponse {
	return &NullableReactionsAndRecastsResponse{value: val, isSet: true}
}

func (v NullableReactionsAndRecastsResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReactionsAndRecastsResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


