/*
Farcaster API V1

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the VerificationResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &VerificationResponse{}

// VerificationResponse struct for VerificationResponse
type VerificationResponse struct {
	Result *VerificationResponseResult `json:"result,omitempty"`
}

// NewVerificationResponse instantiates a new VerificationResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewVerificationResponse() *VerificationResponse {
	this := VerificationResponse{}
	return &this
}

// NewVerificationResponseWithDefaults instantiates a new VerificationResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewVerificationResponseWithDefaults() *VerificationResponse {
	this := VerificationResponse{}
	return &this
}

// GetResult returns the Result field value if set, zero value otherwise.
func (o *VerificationResponse) GetResult() VerificationResponseResult {
	if o == nil || IsNil(o.Result) {
		var ret VerificationResponseResult
		return ret
	}
	return *o.Result
}

// GetResultOk returns a tuple with the Result field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *VerificationResponse) GetResultOk() (*VerificationResponseResult, bool) {
	if o == nil || IsNil(o.Result) {
		return nil, false
	}
	return o.Result, true
}

// HasResult returns a boolean if a field has been set.
func (o *VerificationResponse) HasResult() bool {
	if o != nil && !IsNil(o.Result) {
		return true
	}

	return false
}

// SetResult gets a reference to the given VerificationResponseResult and assigns it to the Result field.
func (o *VerificationResponse) SetResult(v VerificationResponseResult) {
	o.Result = &v
}

func (o VerificationResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o VerificationResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Result) {
		toSerialize["result"] = o.Result
	}
	return toSerialize, nil
}

type NullableVerificationResponse struct {
	value *VerificationResponse
	isSet bool
}

func (v NullableVerificationResponse) Get() *VerificationResponse {
	return v.value
}

func (v *NullableVerificationResponse) Set(val *VerificationResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableVerificationResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableVerificationResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableVerificationResponse(val *VerificationResponse) *NullableVerificationResponse {
	return &NullableVerificationResponse{value: val, isSet: true}
}

func (v NullableVerificationResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableVerificationResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


