/*
Farcaster API V2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the NeynarFramePage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &NeynarFramePage{}

// NeynarFramePage struct for NeynarFramePage
type NeynarFramePage struct {
	// Unique identifier for the page.
	Uuid string `json:"uuid"`
	// The version of the page schema.
	Version string `json:"version"`
	// The title of the page.
	Title   string             `json:"title"`
	Image   NeynarPageImage    `json:"image"`
	Buttons []NeynarPageButton `json:"buttons,omitempty"`
	Input   *NeynarPageInput   `json:"input,omitempty"`
}

type _NeynarFramePage NeynarFramePage

// NewNeynarFramePage instantiates a new NeynarFramePage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewNeynarFramePage(uuid string, version string, title string, image NeynarPageImage) *NeynarFramePage {
	this := NeynarFramePage{}
	this.Uuid = uuid
	this.Version = version
	this.Title = title
	this.Image = image
	return &this
}

// NewNeynarFramePageWithDefaults instantiates a new NeynarFramePage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewNeynarFramePageWithDefaults() *NeynarFramePage {
	this := NeynarFramePage{}
	var version string = "vNext"
	this.Version = version
	return &this
}

// GetUuid returns the Uuid field value
func (o *NeynarFramePage) GetUuid() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value
// and a boolean to check if the value has been set.
func (o *NeynarFramePage) GetUuidOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Uuid, true
}

// SetUuid sets field value
func (o *NeynarFramePage) SetUuid(v string) {
	o.Uuid = v
}

// GetVersion returns the Version field value
func (o *NeynarFramePage) GetVersion() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Version
}

// GetVersionOk returns a tuple with the Version field value
// and a boolean to check if the value has been set.
func (o *NeynarFramePage) GetVersionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Version, true
}

// SetVersion sets field value
func (o *NeynarFramePage) SetVersion(v string) {
	o.Version = v
}

// GetTitle returns the Title field value
func (o *NeynarFramePage) GetTitle() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Title
}

// GetTitleOk returns a tuple with the Title field value
// and a boolean to check if the value has been set.
func (o *NeynarFramePage) GetTitleOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Title, true
}

// SetTitle sets field value
func (o *NeynarFramePage) SetTitle(v string) {
	o.Title = v
}

// GetImage returns the Image field value
func (o *NeynarFramePage) GetImage() NeynarPageImage {
	if o == nil {
		var ret NeynarPageImage
		return ret
	}

	return o.Image
}

// GetImageOk returns a tuple with the Image field value
// and a boolean to check if the value has been set.
func (o *NeynarFramePage) GetImageOk() (*NeynarPageImage, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Image, true
}

// SetImage sets field value
func (o *NeynarFramePage) SetImage(v NeynarPageImage) {
	o.Image = v
}

// GetButtons returns the Buttons field value if set, zero value otherwise.
func (o *NeynarFramePage) GetButtons() []NeynarPageButton {
	if o == nil || IsNil(o.Buttons) {
		var ret []NeynarPageButton
		return ret
	}
	return o.Buttons
}

// GetButtonsOk returns a tuple with the Buttons field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NeynarFramePage) GetButtonsOk() ([]NeynarPageButton, bool) {
	if o == nil || IsNil(o.Buttons) {
		return nil, false
	}
	return o.Buttons, true
}

// HasButtons returns a boolean if a field has been set.
func (o *NeynarFramePage) HasButtons() bool {
	if o != nil && !IsNil(o.Buttons) {
		return true
	}

	return false
}

// SetButtons gets a reference to the given []NeynarPageButton and assigns it to the Buttons field.
func (o *NeynarFramePage) SetButtons(v []NeynarPageButton) {
	o.Buttons = v
}

// GetInput returns the Input field value if set, zero value otherwise.
func (o *NeynarFramePage) GetInput() NeynarPageInput {
	if o == nil || IsNil(o.Input) {
		var ret NeynarPageInput
		return ret
	}
	return *o.Input
}

// GetInputOk returns a tuple with the Input field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *NeynarFramePage) GetInputOk() (*NeynarPageInput, bool) {
	if o == nil || IsNil(o.Input) {
		return nil, false
	}
	return o.Input, true
}

// HasInput returns a boolean if a field has been set.
func (o *NeynarFramePage) HasInput() bool {
	if o != nil && !IsNil(o.Input) {
		return true
	}

	return false
}

// SetInput gets a reference to the given NeynarPageInput and assigns it to the Input field.
func (o *NeynarFramePage) SetInput(v NeynarPageInput) {
	o.Input = &v
}

func (o NeynarFramePage) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o NeynarFramePage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["uuid"] = o.Uuid
	toSerialize["version"] = o.Version
	toSerialize["title"] = o.Title
	toSerialize["image"] = o.Image
	if !IsNil(o.Buttons) {
		toSerialize["buttons"] = o.Buttons
	}
	if !IsNil(o.Input) {
		toSerialize["input"] = o.Input
	}
	return toSerialize, nil
}

func (o *NeynarFramePage) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"uuid",
		"version",
		"title",
		"image",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varNeynarFramePage := _NeynarFramePage{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varNeynarFramePage)

	if err != nil {
		return err
	}

	*o = NeynarFramePage(varNeynarFramePage)

	return err
}

type NullableNeynarFramePage struct {
	value *NeynarFramePage
	isSet bool
}

func (v NullableNeynarFramePage) Get() *NeynarFramePage {
	return v.value
}

func (v *NullableNeynarFramePage) Set(val *NeynarFramePage) {
	v.value = val
	v.isSet = true
}

func (v NullableNeynarFramePage) IsSet() bool {
	return v.isSet
}

func (v *NullableNeynarFramePage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableNeynarFramePage(val *NeynarFramePage) *NullableNeynarFramePage {
	return &NullableNeynarFramePage{value: val, isSet: true}
}

func (v NullableNeynarFramePage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableNeynarFramePage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
