/*
 * Farcaster API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type StorageAllocationsResponse struct {
	TotalActiveUnits int32 `json:"total_active_units,omitempty"`
	Allocations []StorageAllocation `json:"allocations,omitempty"`
}
