/*
Farcaster API V2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the FrameValidateAnalyticsInputText type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &FrameValidateAnalyticsInputText{}

// FrameValidateAnalyticsInputText struct for FrameValidateAnalyticsInputText
type FrameValidateAnalyticsInputText struct {
	InputTexts []FrameValidateAnalyticsInputTextInputTextsInner `json:"input_texts,omitempty"`
}

// NewFrameValidateAnalyticsInputText instantiates a new FrameValidateAnalyticsInputText object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewFrameValidateAnalyticsInputText() *FrameValidateAnalyticsInputText {
	this := FrameValidateAnalyticsInputText{}
	return &this
}

// NewFrameValidateAnalyticsInputTextWithDefaults instantiates a new FrameValidateAnalyticsInputText object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewFrameValidateAnalyticsInputTextWithDefaults() *FrameValidateAnalyticsInputText {
	this := FrameValidateAnalyticsInputText{}
	return &this
}

// GetInputTexts returns the InputTexts field value if set, zero value otherwise.
func (o *FrameValidateAnalyticsInputText) GetInputTexts() []FrameValidateAnalyticsInputTextInputTextsInner {
	if o == nil || IsNil(o.InputTexts) {
		var ret []FrameValidateAnalyticsInputTextInputTextsInner
		return ret
	}
	return o.InputTexts
}

// GetInputTextsOk returns a tuple with the InputTexts field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *FrameValidateAnalyticsInputText) GetInputTextsOk() ([]FrameValidateAnalyticsInputTextInputTextsInner, bool) {
	if o == nil || IsNil(o.InputTexts) {
		return nil, false
	}
	return o.InputTexts, true
}

// HasInputTexts returns a boolean if a field has been set.
func (o *FrameValidateAnalyticsInputText) HasInputTexts() bool {
	if o != nil && !IsNil(o.InputTexts) {
		return true
	}

	return false
}

// SetInputTexts gets a reference to the given []FrameValidateAnalyticsInputTextInputTextsInner and assigns it to the InputTexts field.
func (o *FrameValidateAnalyticsInputText) SetInputTexts(v []FrameValidateAnalyticsInputTextInputTextsInner) {
	o.InputTexts = v
}

func (o FrameValidateAnalyticsInputText) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o FrameValidateAnalyticsInputText) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.InputTexts) {
		toSerialize["input_texts"] = o.InputTexts
	}
	return toSerialize, nil
}

type NullableFrameValidateAnalyticsInputText struct {
	value *FrameValidateAnalyticsInputText
	isSet bool
}

func (v NullableFrameValidateAnalyticsInputText) Get() *FrameValidateAnalyticsInputText {
	return v.value
}

func (v *NullableFrameValidateAnalyticsInputText) Set(val *FrameValidateAnalyticsInputText) {
	v.value = val
	v.isSet = true
}

func (v NullableFrameValidateAnalyticsInputText) IsSet() bool {
	return v.isSet
}

func (v *NullableFrameValidateAnalyticsInputText) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableFrameValidateAnalyticsInputText(val *FrameValidateAnalyticsInputText) *NullableFrameValidateAnalyticsInputText {
	return &NullableFrameValidateAnalyticsInputText{value: val, isSet: true}
}

func (v NullableFrameValidateAnalyticsInputText) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableFrameValidateAnalyticsInputText) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


