/*
 * Farcaster API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// VerificationChainId : Chain ID for farcaster verifications. 0 for EOA verifications, 1 or 10 for contract verifications
type VerificationChainId int32

// List of VerificationChainId
const (
	VerificationChainId__0 VerificationChainId = 0
	VerificationChainId__1 = 1
	VerificationChainId__10 VerificationChainId = 10
)
