/*
 * Farcaster API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type MarkNotificationsAsSeenReqBody struct {
	// The UUID of the signer. Signer should have atleast one write permission 
	SignerUuid string `json:"signer_uuid"`
	Type_ *NotificationType `json:"type,omitempty"`
}
