/*
 * Farcaster API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type WebhookSubscriptionFiltersFollow struct {
	Fids []int32 `json:"fids,omitempty"`
	TargetFids []int32 `json:"target_fids,omitempty"`
}
