/*
 * Farcaster API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FrameAction struct {
	Version string `json:"version,omitempty"`
	Title string `json:"title,omitempty"`
	Image string `json:"image,omitempty"`
	Button *FrameActionButton `json:"button"`
	Input *FrameInput `json:"input,omitempty"`
	State *FrameState `json:"state,omitempty"`
	Transaction *FrameTransaction `json:"transaction,omitempty"`
	Address string `json:"address,omitempty"`
	// URL of the frames
	FramesUrl string `json:"frames_url"`
	// URL of the post to get the next frame
	PostUrl string `json:"post_url"`
}
