/*
 * Farcaster API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type FrameValidateAnalyticsInputTextInputTexts struct {
	Fid int32 `json:"fid"`
	Username string `json:"username"`
	InputText string `json:"input_text"`
}
