/*
 * Farcaster API V2
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 2.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

// Details for the conflict error response
type ConflictErrorRes struct {
	Code string `json:"code,omitempty"`
	Message string `json:"message"`
	Property string `json:"property,omitempty"`
	Key string `json:"key,omitempty"`
}
