/*
Farcaster API V2

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the ChannelActivity type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ChannelActivity{}

// ChannelActivity struct for ChannelActivity
type ChannelActivity struct {
	Object *string `json:"object,omitempty"`
	CastCount1d *string `json:"cast_count_1d,omitempty"`
	CastCount7d *string `json:"cast_count_7d,omitempty"`
	CastCount30d *string `json:"cast_count_30d,omitempty"`
	Channel *Channel `json:"channel,omitempty"`
}

// NewChannelActivity instantiates a new ChannelActivity object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewChannelActivity() *ChannelActivity {
	this := ChannelActivity{}
	return &this
}

// NewChannelActivityWithDefaults instantiates a new ChannelActivity object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewChannelActivityWithDefaults() *ChannelActivity {
	this := ChannelActivity{}
	return &this
}

// GetObject returns the Object field value if set, zero value otherwise.
func (o *ChannelActivity) GetObject() string {
	if o == nil || IsNil(o.Object) {
		var ret string
		return ret
	}
	return *o.Object
}

// GetObjectOk returns a tuple with the Object field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelActivity) GetObjectOk() (*string, bool) {
	if o == nil || IsNil(o.Object) {
		return nil, false
	}
	return o.Object, true
}

// HasObject returns a boolean if a field has been set.
func (o *ChannelActivity) HasObject() bool {
	if o != nil && !IsNil(o.Object) {
		return true
	}

	return false
}

// SetObject gets a reference to the given string and assigns it to the Object field.
func (o *ChannelActivity) SetObject(v string) {
	o.Object = &v
}

// GetCastCount1d returns the CastCount1d field value if set, zero value otherwise.
func (o *ChannelActivity) GetCastCount1d() string {
	if o == nil || IsNil(o.CastCount1d) {
		var ret string
		return ret
	}
	return *o.CastCount1d
}

// GetCastCount1dOk returns a tuple with the CastCount1d field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelActivity) GetCastCount1dOk() (*string, bool) {
	if o == nil || IsNil(o.CastCount1d) {
		return nil, false
	}
	return o.CastCount1d, true
}

// HasCastCount1d returns a boolean if a field has been set.
func (o *ChannelActivity) HasCastCount1d() bool {
	if o != nil && !IsNil(o.CastCount1d) {
		return true
	}

	return false
}

// SetCastCount1d gets a reference to the given string and assigns it to the CastCount1d field.
func (o *ChannelActivity) SetCastCount1d(v string) {
	o.CastCount1d = &v
}

// GetCastCount7d returns the CastCount7d field value if set, zero value otherwise.
func (o *ChannelActivity) GetCastCount7d() string {
	if o == nil || IsNil(o.CastCount7d) {
		var ret string
		return ret
	}
	return *o.CastCount7d
}

// GetCastCount7dOk returns a tuple with the CastCount7d field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelActivity) GetCastCount7dOk() (*string, bool) {
	if o == nil || IsNil(o.CastCount7d) {
		return nil, false
	}
	return o.CastCount7d, true
}

// HasCastCount7d returns a boolean if a field has been set.
func (o *ChannelActivity) HasCastCount7d() bool {
	if o != nil && !IsNil(o.CastCount7d) {
		return true
	}

	return false
}

// SetCastCount7d gets a reference to the given string and assigns it to the CastCount7d field.
func (o *ChannelActivity) SetCastCount7d(v string) {
	o.CastCount7d = &v
}

// GetCastCount30d returns the CastCount30d field value if set, zero value otherwise.
func (o *ChannelActivity) GetCastCount30d() string {
	if o == nil || IsNil(o.CastCount30d) {
		var ret string
		return ret
	}
	return *o.CastCount30d
}

// GetCastCount30dOk returns a tuple with the CastCount30d field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelActivity) GetCastCount30dOk() (*string, bool) {
	if o == nil || IsNil(o.CastCount30d) {
		return nil, false
	}
	return o.CastCount30d, true
}

// HasCastCount30d returns a boolean if a field has been set.
func (o *ChannelActivity) HasCastCount30d() bool {
	if o != nil && !IsNil(o.CastCount30d) {
		return true
	}

	return false
}

// SetCastCount30d gets a reference to the given string and assigns it to the CastCount30d field.
func (o *ChannelActivity) SetCastCount30d(v string) {
	o.CastCount30d = &v
}

// GetChannel returns the Channel field value if set, zero value otherwise.
func (o *ChannelActivity) GetChannel() Channel {
	if o == nil || IsNil(o.Channel) {
		var ret Channel
		return ret
	}
	return *o.Channel
}

// GetChannelOk returns a tuple with the Channel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *ChannelActivity) GetChannelOk() (*Channel, bool) {
	if o == nil || IsNil(o.Channel) {
		return nil, false
	}
	return o.Channel, true
}

// HasChannel returns a boolean if a field has been set.
func (o *ChannelActivity) HasChannel() bool {
	if o != nil && !IsNil(o.Channel) {
		return true
	}

	return false
}

// SetChannel gets a reference to the given Channel and assigns it to the Channel field.
func (o *ChannelActivity) SetChannel(v Channel) {
	o.Channel = &v
}

func (o ChannelActivity) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ChannelActivity) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Object) {
		toSerialize["object"] = o.Object
	}
	if !IsNil(o.CastCount1d) {
		toSerialize["cast_count_1d"] = o.CastCount1d
	}
	if !IsNil(o.CastCount7d) {
		toSerialize["cast_count_7d"] = o.CastCount7d
	}
	if !IsNil(o.CastCount30d) {
		toSerialize["cast_count_30d"] = o.CastCount30d
	}
	if !IsNil(o.Channel) {
		toSerialize["channel"] = o.Channel
	}
	return toSerialize, nil
}

type NullableChannelActivity struct {
	value *ChannelActivity
	isSet bool
}

func (v NullableChannelActivity) Get() *ChannelActivity {
	return v.value
}

func (v *NullableChannelActivity) Set(val *ChannelActivity) {
	v.value = val
	v.isSet = true
}

func (v NullableChannelActivity) IsSet() bool {
	return v.isSet
}

func (v *NullableChannelActivity) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableChannelActivity(val *ChannelActivity) *NullableChannelActivity {
	return &NullableChannelActivity{value: val, isSet: true}
}

func (v NullableChannelActivity) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableChannelActivity) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


