/*
Raw Farcaster Hub API

Perform basic queries of Farcaster state via the REST API of a Farcaster hub. See the [Farcaster docs](https://www.thehubble.xyz/docs/httpapi/httpapi.html) for more details. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the MessageDataVerificationRemove type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MessageDataVerificationRemove{}

// MessageDataVerificationRemove struct for MessageDataVerificationRemove
type MessageDataVerificationRemove struct {
	Fid *int32 `json:"fid,omitempty"`
	Timestamp *int64 `json:"timestamp,omitempty"`
	Network *FarcasterNetwork `json:"network,omitempty"`
	VerificationRemoveBody *VerificationRemoveBody `json:"verificationRemoveBody,omitempty"`
}

// NewMessageDataVerificationRemove instantiates a new MessageDataVerificationRemove object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMessageDataVerificationRemove() *MessageDataVerificationRemove {
	this := MessageDataVerificationRemove{}
	var network FarcasterNetwork = FARCASTERNETWORK_MAINNET
	this.Network = &network
	return &this
}

// NewMessageDataVerificationRemoveWithDefaults instantiates a new MessageDataVerificationRemove object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMessageDataVerificationRemoveWithDefaults() *MessageDataVerificationRemove {
	this := MessageDataVerificationRemove{}
	var network FarcasterNetwork = FARCASTERNETWORK_MAINNET
	this.Network = &network
	return &this
}

// GetFid returns the Fid field value if set, zero value otherwise.
func (o *MessageDataVerificationRemove) GetFid() int32 {
	if o == nil || IsNil(o.Fid) {
		var ret int32
		return ret
	}
	return *o.Fid
}

// GetFidOk returns a tuple with the Fid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageDataVerificationRemove) GetFidOk() (*int32, bool) {
	if o == nil || IsNil(o.Fid) {
		return nil, false
	}
	return o.Fid, true
}

// HasFid returns a boolean if a field has been set.
func (o *MessageDataVerificationRemove) HasFid() bool {
	if o != nil && !IsNil(o.Fid) {
		return true
	}

	return false
}

// SetFid gets a reference to the given int32 and assigns it to the Fid field.
func (o *MessageDataVerificationRemove) SetFid(v int32) {
	o.Fid = &v
}

// GetTimestamp returns the Timestamp field value if set, zero value otherwise.
func (o *MessageDataVerificationRemove) GetTimestamp() int64 {
	if o == nil || IsNil(o.Timestamp) {
		var ret int64
		return ret
	}
	return *o.Timestamp
}

// GetTimestampOk returns a tuple with the Timestamp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageDataVerificationRemove) GetTimestampOk() (*int64, bool) {
	if o == nil || IsNil(o.Timestamp) {
		return nil, false
	}
	return o.Timestamp, true
}

// HasTimestamp returns a boolean if a field has been set.
func (o *MessageDataVerificationRemove) HasTimestamp() bool {
	if o != nil && !IsNil(o.Timestamp) {
		return true
	}

	return false
}

// SetTimestamp gets a reference to the given int64 and assigns it to the Timestamp field.
func (o *MessageDataVerificationRemove) SetTimestamp(v int64) {
	o.Timestamp = &v
}

// GetNetwork returns the Network field value if set, zero value otherwise.
func (o *MessageDataVerificationRemove) GetNetwork() FarcasterNetwork {
	if o == nil || IsNil(o.Network) {
		var ret FarcasterNetwork
		return ret
	}
	return *o.Network
}

// GetNetworkOk returns a tuple with the Network field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageDataVerificationRemove) GetNetworkOk() (*FarcasterNetwork, bool) {
	if o == nil || IsNil(o.Network) {
		return nil, false
	}
	return o.Network, true
}

// HasNetwork returns a boolean if a field has been set.
func (o *MessageDataVerificationRemove) HasNetwork() bool {
	if o != nil && !IsNil(o.Network) {
		return true
	}

	return false
}

// SetNetwork gets a reference to the given FarcasterNetwork and assigns it to the Network field.
func (o *MessageDataVerificationRemove) SetNetwork(v FarcasterNetwork) {
	o.Network = &v
}

// GetVerificationRemoveBody returns the VerificationRemoveBody field value if set, zero value otherwise.
func (o *MessageDataVerificationRemove) GetVerificationRemoveBody() VerificationRemoveBody {
	if o == nil || IsNil(o.VerificationRemoveBody) {
		var ret VerificationRemoveBody
		return ret
	}
	return *o.VerificationRemoveBody
}

// GetVerificationRemoveBodyOk returns a tuple with the VerificationRemoveBody field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MessageDataVerificationRemove) GetVerificationRemoveBodyOk() (*VerificationRemoveBody, bool) {
	if o == nil || IsNil(o.VerificationRemoveBody) {
		return nil, false
	}
	return o.VerificationRemoveBody, true
}

// HasVerificationRemoveBody returns a boolean if a field has been set.
func (o *MessageDataVerificationRemove) HasVerificationRemoveBody() bool {
	if o != nil && !IsNil(o.VerificationRemoveBody) {
		return true
	}

	return false
}

// SetVerificationRemoveBody gets a reference to the given VerificationRemoveBody and assigns it to the VerificationRemoveBody field.
func (o *MessageDataVerificationRemove) SetVerificationRemoveBody(v VerificationRemoveBody) {
	o.VerificationRemoveBody = &v
}

func (o MessageDataVerificationRemove) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MessageDataVerificationRemove) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Fid) {
		toSerialize["fid"] = o.Fid
	}
	if !IsNil(o.Timestamp) {
		toSerialize["timestamp"] = o.Timestamp
	}
	if !IsNil(o.Network) {
		toSerialize["network"] = o.Network
	}
	if !IsNil(o.VerificationRemoveBody) {
		toSerialize["verificationRemoveBody"] = o.VerificationRemoveBody
	}
	return toSerialize, nil
}

type NullableMessageDataVerificationRemove struct {
	value *MessageDataVerificationRemove
	isSet bool
}

func (v NullableMessageDataVerificationRemove) Get() *MessageDataVerificationRemove {
	return v.value
}

func (v *NullableMessageDataVerificationRemove) Set(val *MessageDataVerificationRemove) {
	v.value = val
	v.isSet = true
}

func (v NullableMessageDataVerificationRemove) IsSet() bool {
	return v.isSet
}

func (v *NullableMessageDataVerificationRemove) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMessageDataVerificationRemove(val *MessageDataVerificationRemove) *NullableMessageDataVerificationRemove {
	return &NullableMessageDataVerificationRemove{value: val, isSet: true}
}

func (v NullableMessageDataVerificationRemove) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMessageDataVerificationRemove) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


