/*
Raw Farcaster Hub API

Perform basic queries of Farcaster state via the REST API of a Farcaster hub. See the [Farcaster docs](https://www.thehubble.xyz/docs/httpapi/httpapi.html) for more details. 

API version: 1.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"fmt"
)

// checks if the GetUserDataByFid200ResponseOneOf type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetUserDataByFid200ResponseOneOf{}

// GetUserDataByFid200ResponseOneOf struct for GetUserDataByFid200ResponseOneOf
type GetUserDataByFid200ResponseOneOf struct {
	Messages []UserDataAdd `json:"messages"`
	NextPageToken string `json:"nextPageToken" validate:"regexp=^(?:[A-Za-z0-9+\\/]{4})*(?:[A-Za-z0-9+\\/]{2}==|[A-Za-z0-9+\\/]{3}=)?$"`
	AdditionalProperties map[string]interface{}
}

type _GetUserDataByFid200ResponseOneOf GetUserDataByFid200ResponseOneOf

// NewGetUserDataByFid200ResponseOneOf instantiates a new GetUserDataByFid200ResponseOneOf object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetUserDataByFid200ResponseOneOf(messages []UserDataAdd, nextPageToken string) *GetUserDataByFid200ResponseOneOf {
	this := GetUserDataByFid200ResponseOneOf{}
	this.Messages = messages
	this.NextPageToken = nextPageToken
	return &this
}

// NewGetUserDataByFid200ResponseOneOfWithDefaults instantiates a new GetUserDataByFid200ResponseOneOf object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetUserDataByFid200ResponseOneOfWithDefaults() *GetUserDataByFid200ResponseOneOf {
	this := GetUserDataByFid200ResponseOneOf{}
	return &this
}

// GetMessages returns the Messages field value
func (o *GetUserDataByFid200ResponseOneOf) GetMessages() []UserDataAdd {
	if o == nil {
		var ret []UserDataAdd
		return ret
	}

	return o.Messages
}

// GetMessagesOk returns a tuple with the Messages field value
// and a boolean to check if the value has been set.
func (o *GetUserDataByFid200ResponseOneOf) GetMessagesOk() ([]UserDataAdd, bool) {
	if o == nil {
		return nil, false
	}
	return o.Messages, true
}

// SetMessages sets field value
func (o *GetUserDataByFid200ResponseOneOf) SetMessages(v []UserDataAdd) {
	o.Messages = v
}

// GetNextPageToken returns the NextPageToken field value
func (o *GetUserDataByFid200ResponseOneOf) GetNextPageToken() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.NextPageToken
}

// GetNextPageTokenOk returns a tuple with the NextPageToken field value
// and a boolean to check if the value has been set.
func (o *GetUserDataByFid200ResponseOneOf) GetNextPageTokenOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.NextPageToken, true
}

// SetNextPageToken sets field value
func (o *GetUserDataByFid200ResponseOneOf) SetNextPageToken(v string) {
	o.NextPageToken = v
}

func (o GetUserDataByFid200ResponseOneOf) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetUserDataByFid200ResponseOneOf) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["messages"] = o.Messages
	toSerialize["nextPageToken"] = o.NextPageToken

	for key, value := range o.AdditionalProperties {
		toSerialize[key] = value
	}

	return toSerialize, nil
}

func (o *GetUserDataByFid200ResponseOneOf) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"messages",
		"nextPageToken",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGetUserDataByFid200ResponseOneOf := _GetUserDataByFid200ResponseOneOf{}

	err = json.Unmarshal(data, &varGetUserDataByFid200ResponseOneOf)

	if err != nil {
		return err
	}

	*o = GetUserDataByFid200ResponseOneOf(varGetUserDataByFid200ResponseOneOf)

	additionalProperties := make(map[string]interface{})

	if err = json.Unmarshal(data, &additionalProperties); err == nil {
		delete(additionalProperties, "messages")
		delete(additionalProperties, "nextPageToken")
		o.AdditionalProperties = additionalProperties
	}

	return err
}

type NullableGetUserDataByFid200ResponseOneOf struct {
	value *GetUserDataByFid200ResponseOneOf
	isSet bool
}

func (v NullableGetUserDataByFid200ResponseOneOf) Get() *GetUserDataByFid200ResponseOneOf {
	return v.value
}

func (v *NullableGetUserDataByFid200ResponseOneOf) Set(val *GetUserDataByFid200ResponseOneOf) {
	v.value = val
	v.isSet = true
}

func (v NullableGetUserDataByFid200ResponseOneOf) IsSet() bool {
	return v.isSet
}

func (v *NullableGetUserDataByFid200ResponseOneOf) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetUserDataByFid200ResponseOneOf(val *GetUserDataByFid200ResponseOneOf) *NullableGetUserDataByFid200ResponseOneOf {
	return &NullableGetUserDataByFid200ResponseOneOf{value: val, isSet: true}
}

func (v NullableGetUserDataByFid200ResponseOneOf) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetUserDataByFid200ResponseOneOf) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


